AdminDashBoard/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using AdminDashBoard.Models;
using Newtonsoft.Json;
using System.Text;
using AdminDashBoard.ViewModel;
using Microsoft.AspNetCore.Http;
using ApiContext;
using Domain;

using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;
using System.Data;
using AdminSiteUseMVC.Services.Abstract;

namespace AdminDashBoard.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly DBContext dBContext;
        private readonly IImageServices _imageServices;


        public ProductController(DBContext _dBContext,  IImageServices imageServices)
        {
            dBContext = _dBContext;
            _imageServices = imageServices;
            
        }
        private readonly HttpClient _httpClient = new HttpClient();


        [HttpGet]
        public async Task<IActionResult> Index()//string Lang, int? CategoryId, string? Name, string? ArabicName
        //    , int? Discount, float? Morethan, float? Lessthan
        {
            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }

            var data = dBContext.Products.Select(a => new GetAllProduct
            {
                Id = a.Id,
                Name = a.Name,
                NameArabic = a.NameArabic,
                ImagePath = a.ImagePath,
                Price=a.Price,
                DiscArabic=a.DiscriptionArabic,
                Discription=a.Discription,
                Discount=a.Discount
            });
            return View(data);

        }
        [HttpGet]
        public async Task<IActionResult> Details(long Id)
        {
            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }
            //var apiUrl = $"http://localhost:5000/api/Product/GetProductyById/{Id}";

            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync($"http://ahmedrefaay-001-site1.ctempurl.com/API/api/Product/GetProductyById/{Id}"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    var product = JsonConvert.DeserializeObject<ProductDetails>(apiResponse);
                    return View(product);
                }

            }

        }


        public IActionResult Create()
        {
            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }

            var viewModel = new Models.Product
            {
                category = new SelectList(dBContext.Categories.Select(a=> new GetAllCategory { Id=a.Id ,Name=a.Name}), "Id", "Name")
            };

            return View(viewModel);

        }
        [HttpPost]
        public async Task<IActionResult> Create(Models.Product product)
        {

            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }

            //var file = product.Images;
            //if (file == null || file.Length == 0)
            //    return BadRequest("Please select an image");
            //var fileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";

            ////category.ImagePath = ImageFullPath;
            //string currentDirectory = System.IO.Directory.GetCurrentDirectory();
            //string imagePath = System.IO.Path.Combine(currentDirectory, "CategoryImages");
            //if (!System.IO.Directory.Exists(imagePath))
            //{
            //    System.IO.Directory.CreateDirectory(imagePath);
            //}

            //var filePath = Path.Combine(imagePath, fileName);

            //using (var stream = new FileStream(filePath, FileMode.Create))
            //{
            //    await file.CopyToAsync(stream);
            //}
            //product.ImagePath = $"http://ahmedrefaay-001-site1.ctempurl.com/AdminDashBoard/CategoryImages/{fileName}";
            ////  var category = dBContext.Categories.Where(e => e.Id == product.CategoryId).FirstOrDefault();

            var url = await _imageServices.UploadImageToAzure(product.Images);
            product.ImagePath = url;

            var min = new Domain.Product()
            {
                Name = product.Name,
                NameArabic = product.NameArabic,
                DiscriptionArabic = product.DescriptionArabic,
                Discription = product.Description,
                Discount = product.Discount,
                CategoryId = product.CategoryId,
                Price = product.Price,
                ImagePath = product.ImagePath

            };
            await dBContext.Products.AddAsync(min);
            await dBContext.SaveChangesAsync();
            return RedirectToAction("Index");
            #region
            //using (var client = new HttpClient())
            // {
            //    //var file = product.Images;
            //    //if (file == null || file.Length == 0)
            //    //    return BadRequest("Please select an image");
            //    // var imagesDirectoryPath = Path.Combine(Directory.GetCurrentDirectory(), "Images");
            //    // if (!Directory.Exists(imagesDirectoryPath))
            //    //    Directory.CreateDirectory(imagesDirectoryPath);

            //    //var fileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";
            //    //var filePath = Path.Combine(imagesDirectoryPath, fileName);

            //    //using (var stream = new FileStream(filePath, FileMode.Create))
            //    //{
            //    //    await file.CopyToAsync(stream);
            //    //}
            //    //product.ImagePath = filePath;
            //    //var prod = new
            //    //{
            //    //   Name= product.Name,
            //    //    NameArabic=   product.NameArabic,
            //    //    DescriptionArabic=    product.DescriptionArabic,
            //    //    Discount=   product.Discount,
            //    //    Description=   product.Description,
            //    //    CategoryId=  product.CategoryId,
            //    //    ImagePath= product.ImagePath,
            //    //    AvailUnit = product.AvailUnit,
            //    //    Price= product.Price
            //    //};

            //client.BaseAddress = new Uri("http://localhost:5000/api/Product/CreateProduct");
            //var json = JsonConvert.SerializeObject(product);
            //var content = new StringContent(json, Encoding.UTF8, "multipart/form-data");

            //content.Headers.Remove("Content-Type");
            //content.Headers.TryAddWithoutValidation("Content-Type", "multipart/form-data; charset=ISO-8859-4");

            //var response = await client.PostAsync("http://localhost:5000/api/Product/CreateProduct", content);
            ////var stringContent = new MultipartContent(json, "multipart/form-data");

            ////var response = await client.PostAsync("", stringContent);
            //if (!response.IsSuccessStatusCode)
            //{
            //    throw new Exception("uiu");
            //    return View(product);
            //}
            //return RedirectToAction("Index");

        
        #endregion

    }


        public async Task<IActionResult> Delete(long id)
        {
            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }
            var cat = dBContext.Products.Where(e => e.Id == id).FirstOrDefault();
            if (cat != null)
            {
                dBContext.Products.Remove(cat);
                dBContext.SaveChanges();
                return RedirectToAction("Index");
            }

            else
            {
                return NotFound("Category not found");
            }
        }


        public async Task<IActionResult> Update(long Id)
        {
            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }
            var product = await dBContext.Products.FindAsync(Id);
            if (product == null)
                return NotFound();
            else
            {


                Models.Product min = new Models.Product();
                min.Id = product.Id;
                min.Name = product.Name;
                min.NameArabic = product.NameArabic;
                min.DescriptionArabic = product.DiscriptionArabic;
                min.Description = product.Discription;
                min.Discount = product.Discount;
                min.Price = product.Price;
                min.category = new SelectList(dBContext.Categories.Select(a=> new GetAllCategory {Id=a.Id,Name=a.Name }), "Id", "Name");
                // min.ImagePath = product.ImagePath;


                return View(min);
            }
        }
        [HttpPost]
        public async Task<IActionResult> Update(Models.Product updatedProduct)
        {

            var product = dBContext.Products.FirstOrDefault(p => p.Id == updatedProduct.Id);

            if (product == null)
            {
                return NotFound();
            }
            //var category = dBContext.Categories.Where(e => e.Id == product.category.Id).FirstOrDefault();

            var file = updatedProduct.Images;
            if (file == null || file.Length == 0)
                return BadRequest("Please select an image");
             var fileName = $"{Guid.NewGuid()}{Path.GetExtension(file.FileName)}";

            //category.ImagePath = ImageFullPath;
            string currentDirectory = System.IO.Directory.GetCurrentDirectory();
            string imagePath = System.IO.Path.Combine(currentDirectory, "CategoryImages");
            if (!System.IO.Directory.Exists(imagePath))
            {
                System.IO.Directory.CreateDirectory(imagePath);
            }

AdminDashBoard/Controllers/ReviewController.cs
using AdminDashBoard.ViewModel;
using ApiContext;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace AdminDashBoard.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReviewController : Controller
    {
        private readonly DBContext dBContext;
        private readonly IWebHostEnvironment _env;
        public ReviewController(DBContext _dBContext, IWebHostEnvironment env)
        {
            dBContext = _dBContext;
            _env = env;
        }


        // GET: ReviewController
        public ActionResult Index()
        {

            if (User.Identity.IsAuthenticated == true)
            {
                ViewBag.name = User.Identity.Name;
            }

            ViewBag.product = new SelectList(dBContext.Products.Select(a => new GetAllProduct { Id = a.Id, Name = a.Name }), "Id", "Name");
            ViewBag.UserName = new SelectList(dBContext.Users.Select(a => new GetAllProduct { Id = a.Id, Name = a.UserName }), "Id", "Name");

            



            var data = dBContext.Reviews.Select(a => new GetAllReview
            {
                Id = a.Id,
                Comment = a.Comment,
                 Rate= a.Rate,
                Date = a.Date,
                Username=string.Concat( dBContext.Users.Where(b => b.Id==a.UserId).Select(b=>b.UserName)),
                Productname=string.Concat( dBContext.Products.Where(b => b.Id == a.ProductId).Select(b => b.Name)),
            });
            return View(data);

        }

        // GET: ReviewController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ReviewController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ReviewController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

AdminDashBoard/Views/Shared/_Layout.cshtml
@{
    string name = ViewBag.name;

}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Admin DashBoard</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css" rel="stylesheet" />

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">

    <style>
        .content {
            background-color: #e9ecef !important;
        }
    </style>
</head>

<body>
    <div class="container-fluid position-relative d-flex p-0">
        <!-- Spinner Start -->
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>
        <!-- Spinner End -->
        <!-- Sidebar Start -->
        <!-- Sidebar Start -->
        <div class="sidebar pe-4 pb-3">
            <nav class="navbar bg-secondary navbar-dark">
                <a asp-controller="Home" asp-action="Index" class="navbar-brand mx-4 mb-3">
                    <h3 class="text-primary" asp-controller="Home" asp-action="Index"><i class="fa fa-user-edit me-2"></i>DashBoard</h3>
                </a>
                <div class="d-flex align-items-center ms-4 mb-4">
                    <div class="position-relative">
                        <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                        <div class="bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1"></div>
                    </div>
                    <div class="ms-3">
                        <h6 class="mb-0">Admin</h6>
                        <span>@ViewBag.name</span>
                    </div>
                </div>
                <div class="navbar-nav w-100">
                    <a asp-controller="Home" asp-action="Index" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Category</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Category" asp-action="Create" class="dropdown-item">Add Category</a>
                            <a asp-controller="Category" asp-action="Index" class="dropdown-item">Show Category</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Products</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="Product" asp-action="Create" class="dropdown-item">Add Product</a>
                            <a asp-controller="Product" asp-action="Index" class="dropdown-item">Show Product</a>
                        </div>
                    </div>
                    <a href="widget.html" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Order</a>
                    <a asp-controller="Review" asp-action="Index" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Show All Reviews</a>

                    <a asp-controller="Admin" asp-action="Index" class="nav-item nav-link"><i class="fa fa-th me-2"></i>Show All User</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="far fa-file-alt me-2"></i>Pages</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a asp-controller="AdminAccount" asp-action="LogIN" class="dropdown-item">Sign In</a>
                            <a asp-controller="AdminAccount" asp-action="SignUP" class="dropdown-item">Sign Up</a>
                            <a asp-controller="AdminAccount" asp-action="LogOut" class="dropdown-item">Log Out</a>

                        </div>
                    </div>
                </div>
            </nav>
        </div>
        <!-- Sidebar End -->
        <!-- Content Start -->
        <div class="content bg-body">
            <!-- Navbar Start -->
            <nav class="navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0">
                <a href="index.html" class="navbar-brand d-flex d-lg-none me-4">
                    <h2 class="text-primary mb-0"><i class="fa fa-user-edit"></i></h2>
                </a>
                <a href="#" class="sidebar-toggler flex-shrink-0">
                    <i class="fa fa-bars"></i>
                </a>
                <form class="d-none d-md-flex ms-4">
                    <input class="form-control bg-dark border-0" type="search" placeholder="Search">
                </form>
                <div class="navbar-nav align-items-center ms-auto">
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-envelope me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Message</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <div class="d-flex align-items-center">
                                    <img class="rounded-circle" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                                    <div class="ms-2">
                                        <h6 class="fw-normal mb-0">Jhon send you a message</h6>
                                        <small>15 minutes ago</small>
                                    </div>
                                </div>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all message</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <i class="fa fa-bell me-lg-2"></i>
                            <span class="d-none d-lg-inline-flex">Notificatin</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Profile updated</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">New user added</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item">
                                <h6 class="fw-normal mb-0">Password changed</h6>
                                <small>15 minutes ago</small>
                            </a>
                            <hr class="dropdown-divider">
                            <a href="#" class="dropdown-item text-center">See all notifications</a>
                        </div>
                    </div>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">
                            <img class="rounded-circle me-lg-2" src="~/img/user.jpg" alt="" style="width: 40px; height: 40px;">
                            <span class="d-none d-lg-inline-flex">@name</span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0">
                            <a asp-controller="Admin" asp-action="Detailsadmin" class="dropdown-item">My Profile</a>
                            <a href="#" class="dropdown-item">Settings</a>
                            <a asp-controller="AdminAccount" asp-action="LogOut" class="dropdown-item">Log Out</a>
                        </div>
                    </div>
                </div>
            </nav>
            <!-- Navbar End -->
            <!-- Sale & Revenue Start -->
            <div class="container-fluid pt-4 px-4 ">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
            <!-- Footer Start -->
            <div class="container-fluid pt-4 px-4">
                <div class="bg-secondary rounded-top p-4">
                    <div class="row">
                        <div class="col-12 col-sm-6 text-center text-sm-start">
                            &copy; <a href="#">Your Site Name</a>, All Right Reserved.
                        </div>
                        <div class="col-12 col-sm-6 text-center text-sm-end">
                            <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                            Designed By <a href="https://htmlcodex.com">HTML Codex</a>
                            <br>Distributed By: <a href="https://themewagon.com" target="_blank">ThemeWagon</a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Footer End -->
        </div>
        <!-- Content End -->
        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>

    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/chart/chart.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment.min.js"></script>
    <script src="~/lib/tempusdominus/js/moment-timezone.min.js"></script>
    <script src="~/lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>